config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :counterparties
  resources :groups_counterparties
  resources :goods

  resources :users do
    member do
      put 'block', to: 'blockingusers#block'
      put 'unblock', to: 'blockingusers#unblock'
    end

    collection do
      get 'search', to: 'search#show'
    end
  end

  namespace :admin do
    resources :users do
      member do
        put 'block', to: 'blockingusers#block'
        put 'unblock', to: 'blockingusers#unblock'
      end
    end
  end

  namespace :profile do
    resources :user, except: [:new, :create]
  end

  root to: "home#index"
end

__END__
# ресурс -> URL -> тип (.mp3 .js .css .html .xml .mp4 .ttf)
  # hypertext transfer protocol
  # http://    mail.ru:  8080   /media/video_234                       .mp4
  # ПРОТОКОЛ - ХОСТ -    ПОРТ - ОТНОСИТЕЛЬНЫЙ АДРЕС РЕСУРСА на хосте - ТИП ресурса
  # sftp://

#  data                         data
#   |                            |
#  ftp          spy             ftp
#   |____________|_______________|
#   |                            |
#  ssh                          ssh
#   |____________________________|
#   |                            |
#  tcp/ip                      tcp/ip
#   |____________________________|


  #HTTP specification
  # GET PUT POST DELETE OPTION

  # список ресурсов данного вида            -> index GET
  # конкретный ресурс                       -> show  GET
  # создать ресурс  POST           (create) -> new   GET
  # изменить ресурс PUT            (update) -> edit  GET
  # удалить ресурс  DELETE         (destroy)

app/models/good.rb
class Good < ApplicationRecord
  validates :name, presence: true
  self.per_page = 5
end

app/controllers/goods_controller.rb
class GoodsController < ApplicationController
  before_action :load_model, only: [:show, :edit, :update, :destroy]

  def index
    @goods = Good.order(:name).paginate(:page => params[:page])
  end

  def show
  end

  def new
    @good = Good.new
  end

  def create
    @good = Good.new good_params
    if @good.save
      redirect_to goods_url
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @good.update good_params
      redirect_to goods_url
    else
      render :edit
    end
  end

  def destroy
    @good.destroy
    redirect_to goods_url
  end

  private

  def good_params
    params.require(:good).permit(:name, :comment)
  end

  def load_model
    @good = Good.find params[:id]
  end
end

app/helpers/goods_helper.rb
module GoodsHelper
end

app/views/goods/_form.html.erb
<%= simple_form_for @good do |f| %>
    <%= f.input :name, autofocus: true, label: 'Название' %>
    <%= f.input :comment, placeholder: 'Текст', label: 'Описание' %>
    <%= f.button :submit, 'Сохранить', class: 'btn btn-primary' %>
    <%= link_to 'Отменить', goods_path, class: 'btn btn-default' %>
<% end %>

app/views/goods/_good.html.erb
<tbody>
<% @goods.each_with_index do |good, index| %>
    <tr>
      <td class="td-18 td-right"><%= index + 1 %></td>
      <td class="td-18"><%= link_to icon('fa-edit', 'редактировать'), edit_good_path(good) %></td>
      <td class="td-18 td-right"><%= good.id %></td>
      <td><%= link_to good.name, good_path(good) %></td>
      <td><%= truncate good.comment %></td>
      <td class="td-18"><%= link_to icon('fa-trash', 'удалить'), good_path(good),
                                    method: :delete, data: {confirm: 'Действительно удалить?'} %></td>
    </tr>
<% end %>
</tbody>

app/views/goods/_thead.html.erb
<thead>
<tr>
  <th>№</th>
  <th></th>
  <th>ID</th>
  <th>Название</th>
  <th>Описание</th>
  <th></th>
</tr>
</thead>

app/views/goods/edit.html.erb
<div class="row">
  <div class="col-xs-8 col-xs-offset-2">

    <h1>Редактировать товар</h1>

    <%= render 'goods/form' %>
  </div>
</div>

app/views/goods/index.html.erb
<div class="row">
  <div class="col-xs-8">
    <h1>Номенклатура (<%= @goods.count %>)</h1>
  </div>
  <div class="col-xs-4">
    <div class="pull-right">
      <%= link_to 'Новый', new_good_path, class: 'btn btn-primary btn-sm mg-top-24' %>
    </div>
  </div>
</div>
<%= will_paginate @goods, renderer: BootstrapPagination::Rails %>
<table class="table table-bordered table-hover">
  <%= render 'goods/thead' %>
  <%= render 'goods/good' %>
</table>
<%= will_paginate @goods, renderer: BootstrapPagination::Rails %>

app/views/goods/new.html.erb
<div class="row">
  <div class="col-xs-8 col-xs-offset-2">

    <h1>Новый товар</h1>

    <%= render 'goods/form' %>
  </div>
</div>

app/views/goods/show.html.erb
<h1><%= @good.name %></h1>
<p>
  <%= @good.comment %>
</p>
<p>
  <%= link_to 'Вернуться к списку', goods_path, class: 'btn btn-default' %>
</p>