config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :counterparties
  resources :groups_counterparties
  resources :goods

  resources :users do
    member do
      put 'block', to: 'blockingusers#block'
      put 'unblock', to: 'blockingusers#unblock'
    end

    collection do
      get 'search', to: 'search#show'
    end
  end

  namespace :admin do
    resources :users do
      member do
        put 'block', to: 'blockingusers#block'
        put 'unblock', to: 'blockingusers#unblock'
      end
    end
  end

  namespace :profile do
    resources :user, except: [:new, :create]
  end

  root to: "home#index"
end

__END__
# ресурс -> URL -> тип (.mp3 .js .css .html .xml .mp4 .ttf)
  # hypertext transfer protocol
  # http://    mail.ru:  8080   /media/video_234                       .mp4
  # ПРОТОКОЛ - ХОСТ -    ПОРТ - ОТНОСИТЕЛЬНЫЙ АДРЕС РЕСУРСА на хосте - ТИП ресурса
  # sftp://

#  data                         data
#   |                            |
#  ftp          spy             ftp
#   |____________|_______________|
#   |                            |
#  ssh                          ssh
#   |____________________________|
#   |                            |
#  tcp/ip                      tcp/ip
#   |____________________________|


  #HTTP specification
  # GET PUT POST DELETE OPTION

  # список ресурсов данного вида            -> index GET
  # конкретный ресурс                       -> show  GET
  # создать ресурс  POST           (create) -> new   GET
  # изменить ресурс PUT            (update) -> edit  GET
  # удалить ресурс  DELETE         (destroy)

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  attr_accessor :login

  def self.find_for_database_authentication warden_conditions
    conditions = warden_conditions.dup
    login = conditions.delete(:login)
    where(conditions).where(["lower(username) = :value OR lower(email) = :value", {value: login.strip.downcase}]).first
  end

  validates :username, presence: true, length: { maximum: 50 },
            uniqueness: { case_sensitive: false }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 50 },
            format: { with: VALID_EMAIL_REGEX },
            uniqueness: { case_sensitive: false }

  self.per_page = 5
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < Admin::BaseController

  before_action :load_model, only: [:show, :edit, :update, :destroy]

  def index
    @users = User.order(:email).paginate(:page => params[:page])
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new user_params

    if @user.save
      redirect_to admin_users_path
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @user.update user_params
      redirect_to admin_users_path
    else
      render :edit
    end
  end

  def destroy
    @user.destroy
    redirect_to admin_users_path
  end

  private

  def user_params
    params.require(:user).permit(:username, :email, :password)
  end

  def load_model
    @user = User.find params[:id]
  end
end

app/controllers/profile/user_controller.rb
class Profile::UserController < ApplicationController
  before_action :authenticate_user!
  before_action :load_model, only: [:show, :edit, :update, :destroy]

  def show
  end

  def edit
  end

  def update
    if @user.update user_params

      redirect_to profile_user_path @user
    else
      render :edit
    end
  end

  def destroy
    @user.destroy
    redirect_to root_path
  end

  private

  def user_params
    params.require(:user).permit(:username, :email, :password)
  end

  def load_model
    @user = current_user
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_action :load_model, only: [:show, :edit, :update, :destroy]

  def index
    @users = User.order(:email).paginate(:page => params[:page])
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new user_params

    if @user.save
      redirect_to users_path
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @user.update user_params
      redirect_to users_path
    else
      render :edit
    end
  end

  def destroy
    @user.destroy
    redirect_to users_path
  end

  private

  def user_params
    params.require(:user).permit(:username, :email, :password)
  end

  def load_model
    @user = User.find params[:id]
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/users/_form.html.erb
<%= simple_form_for @user do |f| %>
    <%= f.input :username, autofocus: true, label: 'Логин' %>
    <%= f.input :email, placeholder: 'user@domain.com' %>
    <%= f.input :password, autocomplete: "off", label: "Пароль: <em> 6 символов минимум </em>".html_safe  %>
    <%= f.input :password_confirmation, autocomplete: "off", label: 'Введите пароль еще раз' %>
    <%= f.button :submit, 'Сохранить', class: 'btn btn-primary' %>
    <%#= link_to 'Отменить', admin_users_path, class: 'btn btn-default' %>
<% end %>

app/views/admin/users/_thead.html.haml
%thead
  %tr
    %th №
    %th
    %th ID
    %th login
    %th Email
    %th
    %th

app/views/admin/users/_user.html.haml
- @users.each_with_index do |user, index|
  %tbody
    -if user.block?
      %tr.blocked
        %td.td-18.td-right= index + 1
        %td.td-18= link_to icon('fa-edit', 'редактировать'), edit_admin_user_path(user)
        %td.td-18.td-right= user.id
        %td.my-line-through
          = link_to user.username, admin_user_path(user)
        %td.td-18.my-line-through= link_to user.email, admin_user_path(user)
        %td.td-18= link_to icon('fa-trash', 'удалить'), admin_user_path(user), method: :delete, data: {confirm: 'Действительно удалить?'}
        %td.td-18= link_to icon('fa-toggle-on', 'разблокировать'), unblock_admin_user_path(user), method: 'put', class: 'block'

    - else
      %tr
        %td.td-18.td-right= index + 1
        %td.td-18= link_to icon('fa-edit', 'редактировать'), edit_admin_user_path(user)
        %td.td-18.td-right= user.id
        %td= link_to user.username, admin_user_path(user)
        %td.td-18= link_to user.email, admin_user_path(user)
        %td.td-18= link_to icon('fa-trash', 'удалить'), admin_user_path(user), method: :delete, data: {confirm: 'Действительно удалить?'}
        %td.td-18= link_to icon('fa-toggle-on block', 'заблокировать'), block_admin_user_path(user), method: 'put', class: 'block'

app/views/admin/users/edit.html.erb
<div class="row">
  <div class="col-xs-8 col-xs-offset-2">

    <h1>Редактировать пользователя</h1>

    <%= render 'users/form' %>
  </div>
</div>

app/views/admin/users/index.html.haml
.row
  .col-xs-8
    %h1
      Пользователи
      = @users.count
  .col-xs-4
    .pull-right
      = link_to 'Новый', new_user_path, class: 'btn btn-primary btn-sm mg-top-24'

%table.table.table-bordered.table-hover
  = will_paginate @users, renderer: BootstrapPagination::Rails
  = render 'admin/users/thead'
  = render 'admin/users/user', locals: {row_index: @row_index}
= will_paginate @users, renderer: BootstrapPagination::Rails

app/views/admin/users/new.html.erb
<div class="row">
  <div class="col-xs-8 col-xs-offset-2">

<h1>Новый пользователь</h1>

<%= render 'users/form' %>
  </div>
</div>

app/views/admin/users/show.html.erb
<h1>
  <%= @user.username %>
</h1>
<p>
  <%= @user.email %>
</p>
<p>
  <%= link_to 'Вернуться к списку', admin_users_path, class: 'btn btn-default' %>
</p>